# Serena Project Configuration for HeritageWhisperV2

# Project metadata
project_name: HeritageWhisperV2
description: AI-powered storytelling platform for seniors to capture and share life memories

# Primary language for the project
language: typescript

# File patterns to include in indexing
include_patterns:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.css"
  - "**/*.sql"
  - "**/*.json"
  - "**/*.md"

# File patterns to exclude from indexing
exclude_patterns:
  - "node_modules/**"
  - ".next/**"
  - "dist/**"
  - "build/**"
  - ".git/**"
  - "*.min.js"
  - "*.min.css"
  - "coverage/**"
  - ".vercel/**"
  - "*.log"
  - "*.lock"